---
namespace: middleware_automation
name: infinispan
version: "1.1.3"
readme: README.md
authors:
  - Romain Pelisse <rpelisse@redhat.com>
  - Matthew Fernandez <matferna@redhat.com>
  - Guido Grazioli <ggraziol@redhat.com>
description: Install and configure an Infinispan or DataGrid service.
license_file: "LICENSE"
tags:
  - infinispan
  - datagrid
  - redhat
  - rhel
  - server
  - database
  - infrastructure
  - runtimes
  - middleware
  - a4mw
dependencies:
  "middleware_automation.common": ">=1.0.0"
  "ansible.posix": ">=1.4.0"
repository: https://github.com/ansible-middleware/infinispan
documentation: https://ansible-middleware.github.io/infinispan
homepage: https://github.com/ansible-middleware/infinispan
issues: https://github.com/ansible-middleware/infinispan/issues
build_ignore:
  - .gitignore
  - .github
  - .ansible-lint
  - .yamllint
  - '*.tar.gz'
  - '*.zip'
  - molecule
  - changelogs
  - docs/_gh_include
  - docs/conf.py
  - docs/roles.rst.template
  - docs/requirements.yml
